"""Provider-neutral contracts for the local identity-aware model gateway."""

from wmo.runtime.gateway.contracts import (
    AuthorizationSnapshot,
    CompatibilityDisposition,
    CompatibilityField,
    CompatibilityManifest,
    DirectTarget,
    ExecutionSnapshot,
    GatewayApiSurface,
    GatewayEvent,
    GatewayEventKind,
    GatewayFailure,
    GatewayFailureClass,
    GatewayMessage,
    GatewayRequest,
    GatewayTarget,
    GatewayToolDefinition,
    GatewayUsage,
    ProjectSelection,
    ProjectTarget,
    StructuredTextFormat,
)
from wmo.runtime.gateway.interfaces import (
    AttemptLedger,
    GatewayClock,
    GatewayControlStore,
    ProjectTargetResolver,
    ProviderStream,
    SecretResolver,
)

__all__ = [
    "AttemptLedger",
    "AuthorizationSnapshot",
    "CompatibilityDisposition",
    "CompatibilityField",
    "CompatibilityManifest",
    "DirectTarget",
    "ExecutionSnapshot",
    "GatewayApiSurface",
    "GatewayClock",
    "GatewayControlStore",
    "GatewayEvent",
    "GatewayEventKind",
    "GatewayFailure",
    "GatewayFailureClass",
    "GatewayMessage",
    "GatewayRequest",
    "GatewayTarget",
    "GatewayToolDefinition",
    "GatewayUsage",
    "ProjectSelection",
    "ProjectTarget",
    "ProjectTargetResolver",
    "ProviderStream",
    "SecretResolver",
    "StructuredTextFormat",
]
