"""Canonical model identities and data contracts."""

from wmo.common.models.catalog import (
    ConnectionConfig,
    ModelCatalog,
    ModelCatalogError,
    ModelRecord,
    ModelRoles,
    load_model_catalog,
    write_model_catalog,
)
from wmo.common.models.client import EmbeddingClient, ModelClient
from wmo.common.models.model import (
    AssistantAction,
    Embedding,
    ModelAlias,
    ModelCapabilities,
    ModelFinishReason,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ModelSnapshot,
    NumericMeasurement,
    OperationEconomics,
    RoutedCandidateSnapshot,
    ToolCall,
    ToolChoice,
    Usage,
)

__all__ = [
    "AssistantAction",
    "ConnectionConfig",
    "Embedding",
    "EmbeddingClient",
    "ModelCatalog",
    "ModelCatalogError",
    "ModelAlias",
    "ModelCapabilities",
    "ModelFinishReason",
    "ModelClient",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "ModelRecord",
    "ModelRoles",
    "ModelSnapshot",
    "NumericMeasurement",
    "OperationEconomics",
    "RoutedCandidateSnapshot",
    "ToolCall",
    "ToolChoice",
    "Usage",
    "load_model_catalog",
    "write_model_catalog",
]
