"""Canonical model identities and data contracts."""

from wmo.common.models.catalog import (
    ConnectionConfig,
    ModelCatalog,
    ModelCatalogError,
    ModelRecord,
    ModelRoles,
    SFTModelProvenance,
    load_model_catalog,
    write_model_catalog,
)
from wmo.common.models.client import EmbeddingClient, IdempotentModelClient, ModelClient
from wmo.common.models.model import (
    AssistantAction,
    Embedding,
    ModelAlias,
    ModelCapabilities,
    ModelFinishReason,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ModelSnapshot,
    NumericMeasurement,
    OperationEconomics,
    RoutedCandidateSnapshot,
    ToolCall,
    ToolChoice,
    Usage,
)
from wmo.common.models.pricing import (
    CandidateTokenPrice,
    EmbeddingCostReservation,
    PricingSnapshot,
    load_pricing_snapshot,
)
from wmo.common.models.setup import (
    EMPTY_CATALOG_SHA256,
    ProviderConnection,
    ProviderModelSelection,
    ProviderSetup,
    ProviderSetupError,
    catalog_state_sha256,
    configure_provider_catalog,
)

__all__ = [
    "AssistantAction",
    "CandidateTokenPrice",
    "ConnectionConfig",
    "Embedding",
    "EmbeddingClient",
    "EmbeddingCostReservation",
    "IdempotentModelClient",
    "EMPTY_CATALOG_SHA256",
    "ModelCatalog",
    "ModelCatalogError",
    "ModelAlias",
    "ModelCapabilities",
    "ModelFinishReason",
    "ModelClient",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "ModelRecord",
    "ModelRoles",
    "ModelSnapshot",
    "NumericMeasurement",
    "OperationEconomics",
    "PricingSnapshot",
    "ProviderConnection",
    "ProviderModelSelection",
    "ProviderSetup",
    "ProviderSetupError",
    "RoutedCandidateSnapshot",
    "SFTModelProvenance",
    "ToolCall",
    "ToolChoice",
    "Usage",
    "catalog_state_sha256",
    "configure_provider_catalog",
    "load_model_catalog",
    "load_pricing_snapshot",
    "write_model_catalog",
]
