"""Type stubs for the exp_gateway_native extension module."""

from collections.abc import Callable, Mapping
from typing import Literal, Protocol, overload

__version__: str

class _ControlPlane(Protocol):
    """The callback surface the data plane requires (see NativeControlPlane)."""

    def authenticate(self, argument: str) -> str: ...
    def admit(self, argument: str) -> str: ...
    def sign_dispatch(self, argument: str) -> str: ...
    def start_attempt(self, argument: str) -> str: ...
    def abandon(self, argument: str) -> str: ...
    def claim_scope(self, argument: str) -> str: ...
    def remember(self, argument: str) -> str: ...
    def enforce_output(self, argument: str) -> str: ...
    def settle(self, argument: str) -> str: ...
    def models(self, argument: str) -> str: ...
    def model_detail(self, argument: str) -> str: ...
    def usage_json(self, argument: str) -> str: ...
    def usage_page(self, argument: str) -> str: ...
    def metrics_json(self, argument: str) -> str: ...
    def metrics_text(self, argument: str) -> str: ...
    def readiness(self, argument: str) -> str: ...
    def close_thread_resources(self, argument: str) -> str: ...

class _DeterministicDetector(Protocol):
    """The compiled-rule surface the data plane accepts (see RegexDetector)."""

    def redact(self, text: str) -> str | None: ...
    def matches(self, text: str) -> bool: ...

class RegexDetector:
    """One compiled deterministic guardrail rule owned by the data plane."""

    def __init__(self, spec_json: str) -> None: ...
    def redact(self, text: str) -> str | None: ...
    def matches(self, text: str) -> bool: ...

class ShutdownHandle:
    """Embedder-owned stop signal for one `serve` call."""

    def request_shutdown(self) -> None: ...

class CaptureCollector:
    """Bounded native content capture with an off-path persistence destination."""

    def __init__(self, config_json: str, sink: Callable[[str], None]) -> None: ...
    @staticmethod
    @overload
    def batched(
        config_json: str,
        sink: Callable[[tuple[str, ...]], list[bool]],
        *,
        completion_references: bool = False,
        bytes_output: Literal[False] = False,
    ) -> CaptureCollector: ...
    @staticmethod
    @overload
    def batched(
        config_json: str,
        sink: Callable[[tuple[bytes, ...]], list[bool]],
        *,
        completion_references: bool = False,
        bytes_output: Literal[True],
    ) -> CaptureCollector: ...
    @staticmethod
    def sqlite(config_json: str, local_json: str) -> CaptureCollector | None: ...
    def begin(self, request_json: str) -> bool: ...
    def begin_bytes(self, request_json: bytes) -> bool: ...
    def select_model(self, request_id: str, model_id: str) -> None: ...
    def claim_relay(self, request_id: str) -> bool: ...
    def finish_relay(self, request_id: str, metadata_json: str, body: bytes) -> bool: ...
    def settle(self, request_id: str, keep_prompt: bool, keep_response: bool) -> None: ...
    def close(self, timeout_seconds: float = 10.0) -> bool: ...
    def counts(self) -> tuple[int, int, int, int, int, int]: ...
    def maintenance_failures(self) -> int: ...

def shutdown_handle() -> ShutdownHandle: ...
def serve(
    control_plane: _ControlPlane,
    config_json: str,
    shutdown: ShutdownHandle | None = None,
    on_listening: Callable[[], None] | None = None,
    guardrail_detectors: Mapping[str, _DeterministicDetector] | None = None,
    capture: CaptureCollector | None = None,
) -> None: ...
def metrics_snapshot_json() -> str: ...
def encode_chat_fixture(
    request_id: str,
    model: str,
    created_at: int,
    include_usage: bool,
    events_json: str,
) -> list[str]: ...
def encode_responses_fixture(
    request_id: str,
    model: str,
    created_at: int,
    envelope_json: str,
    events_json: str,
) -> list[str]: ...
def completed_responses_fixture(
    request_id: str,
    model: str,
    created_at: int,
    envelope_json: str,
    events_json: str,
) -> str: ...
def encode_messages_fixture(
    request_id: str,
    model: str,
    events_json: str,
) -> list[str]: ...
def completed_messages_fixture(
    request_id: str,
    model: str,
    events_json: str,
) -> str: ...
def anthropic_error_fixture(public_error_json: str) -> str: ...
def normalize_stream_fixture(dialect: str, chunks_json: str) -> str: ...
def failure_public_error_fixture(failure_class: str, safe_message: str) -> str: ...
