"""Type stubs for the exp_gateway_native extension module."""

from typing import Protocol

__version__: str

class _ControlPlane(Protocol):
    """The callback surface the data plane requires (see NativeControlPlane)."""

    def authenticate(self, argument: str) -> str: ...
    def admit(self, argument: str) -> str: ...
    def sign_dispatch(self, argument: str) -> str: ...
    def start_attempt(self, argument: str) -> str: ...
    def abandon(self, argument: str) -> str: ...
    def claim_scope(self, argument: str) -> str: ...
    def remember(self, argument: str) -> str: ...
    def enforce_output(self, argument: str) -> str: ...
    def settle(self, argument: str) -> str: ...
    def models(self, argument: str) -> str: ...
    def model_detail(self, argument: str) -> str: ...
    def usage_json(self, argument: str) -> str: ...
    def usage_page(self, argument: str) -> str: ...
    def metrics_json(self, argument: str) -> str: ...
    def metrics_text(self, argument: str) -> str: ...
    def readiness(self, argument: str) -> str: ...

class ShutdownHandle:
    """Embedder-owned stop signal for one `serve` call."""

    def request_shutdown(self) -> None: ...

def shutdown_handle() -> ShutdownHandle: ...
def serve(
    control_plane: _ControlPlane,
    config_json: str,
    shutdown: ShutdownHandle | None = None,
) -> None: ...
def metrics_snapshot_json() -> str: ...
def encode_chat_fixture(
    request_id: str,
    model: str,
    created_at: int,
    include_usage: bool,
    events_json: str,
) -> list[str]: ...
def encode_responses_fixture(
    request_id: str,
    model: str,
    created_at: float,
    envelope_json: str,
    events_json: str,
) -> list[str]: ...
def completed_responses_fixture(
    request_id: str,
    model: str,
    created_at: float,
    envelope_json: str,
    events_json: str,
) -> str: ...
def encode_messages_fixture(
    request_id: str,
    model: str,
    events_json: str,
) -> list[str]: ...
def completed_messages_fixture(
    request_id: str,
    model: str,
    events_json: str,
) -> str: ...
def anthropic_error_fixture(public_error_json: str) -> str: ...
def normalize_stream_fixture(dialect: str, chunks_json: str) -> str: ...
def failure_public_error_fixture(failure_class: str, safe_message: str) -> str: ...
