"""Execute-only access to tool observations generated by the text world model."""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager, nullcontext
from dataclasses import dataclass

from exp.common.models import ToolCall
from exp.common.tasks import TaskCase
from exp.runtime.environments import EnvironmentSession, Observation


class SimulatedToolUseError(RuntimeError):
    """An agent requested an observation outside its simulated candidate action."""


@dataclass(frozen=True)
class SimulatedEnvironmentSession:
    """Deliver generated results without invoking any external tool implementation.

    Attributes:
        observe: Required callback resolving an exact pending call into its generated result.
    """

    observe: Callable[[ToolCall], Observation]

    def execute(self, action: ToolCall) -> Observation:
        """Return the generated result for the exact pending candidate tool invocation."""
        return self.observe(action)


@dataclass(frozen=True)
class SimulatedEnvironmentRuntime:
    """Open an execute-only facade over one rollout's generated tool observations.

    Attributes:
        observe: Required rollout-local callback shared with the opened session.
    """

    observe: Callable[[ToolCall], Observation]

    def open(self, task: TaskCase) -> AbstractContextManager[EnvironmentSession]:
        """Bind the episode's environment to its isolated observation provider."""
        del task
        return nullcontext(SimulatedEnvironmentSession(self.observe))
