"""Private per-installation interception certificates and macOS trust setup."""

from __future__ import annotations

import os
import shlex
import stat
import subprocess
import tempfile
from pathlib import Path

from cryptography import x509
from mitmproxy.certs import CertStore


def prepare_certificate(directory: Path) -> Path:
    """Create or reuse a user-owned capture CA without sharing private keys.

    Args:
        directory: Dedicated capture certificate directory.

    Returns:
        Public certificate path suitable for the macOS trust store.

    Raises:
        ValueError: The directory or existing key material is not privately owned.
    """
    for ancestor in (directory, *directory.parents):
        if ancestor.is_symlink():
            raise ValueError(
                "Capture certificate directory must be a user-owned directory without links."
            )
    directory.mkdir(parents=True, mode=0o700, exist_ok=True)
    info = directory.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid():
        raise ValueError("Capture certificate directory must be a user-owned directory.")
    directory.chmod(0o700)
    for path in directory.iterdir():
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_nlink != 1:
            raise ValueError("Capture certificate directory contains unsafe files.")
        path.chmod(0o600)
    old_mask = os.umask(0o077)
    try:
        if not (directory / "mitmproxy-ca.pem").exists():
            CertStore.create_store(
                directory,
                "mitmproxy",
                2048,
                organization="Experiential Labs",
                cn="Experiential Capture",
            )
        CertStore.from_store(str(directory), "mitmproxy", 2048)
    finally:
        os.umask(old_mask)
    return directory / "mitmproxy-ca-cert.pem"


def certificate_is_trusted(certificate: Path, domains: tuple[str, ...]) -> bool:
    """Verify a locally signed TLS leaf for each intended host using macOS trust.

    Explicit roots are deliberately omitted so verification cannot bypass the
    user's installed trust policy. Only public leaf certificates touch disk.
    """
    if not domains:
        return False
    store = CertStore.from_files(
        certificate.parent / "mitmproxy-ca.pem", certificate.parent / "mitmproxy-dhparam.pem"
    )
    with tempfile.TemporaryDirectory(prefix="verify-", dir=certificate.parent) as temporary:
        leaf = Path(temporary) / "leaf.pem"
        for domain in domains:
            descriptor = os.open(leaf, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
            with os.fdopen(descriptor, "wb") as output:
                output.write(store.get_cert(domain, [x509.DNSName(domain)]).cert.to_pem())
            result = subprocess.run(
                [
                    "/usr/bin/security",
                    "verify-cert",
                    "-p",
                    "ssl",
                    "-n",
                    domain,
                    "-c",
                    str(leaf),
                    "-c",
                    str(certificate),
                    "-L",
                ],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=15,
                check=False,
            )
            if result.returncode:
                return False
    return True


def trust_certificate(certificate: Path, domains: tuple[str, ...]) -> None:
    """Request persistent user trust for this CA under hostname-specific TLS policies.

    Args:
        certificate: Public certificate generated by prepare_certificate.
        domains: Exact hostnames captured by the local proxy.

    Raises:
        ValueError: Trust installation is declined or cannot be verified.
    """
    if not domains:
        raise ValueError("Capture certificate trust requires at least one provider hostname.")
    keychain = _user_keychain()
    # One call replaces this certificate's user-domain policy with all hostnames.
    # Repeated calls per host would replace, rather than append, its constraints.
    result = subprocess.run(
        [
            "/usr/bin/security",
            "add-trusted-cert",
            "-r",
            "trustRoot",
            "-p",
            "ssl",
            *(argument for domain in domains for argument in ("-s", domain)),
            "-k",
            str(keychain),
            str(certificate),
        ],
        check=False,
        timeout=180,
        env={"PATH": "/usr/bin:/bin:/usr/sbin:/sbin"},
    )
    if result.returncode or not certificate_is_trusted(certificate, domains):
        raise ValueError("Capture certificate trust was not installed. Run exp capture to retry.")


def _user_keychain() -> Path:
    """Resolve an existing user-owned default keychain without changing preferences."""
    result = subprocess.run(
        ["/usr/bin/security", "default-keychain", "-d", "user"],
        capture_output=True,
        text=True,
        check=False,
        timeout=15,
    )
    paths = shlex.split(result.stdout)
    if result.returncode or len(paths) != 1:
        raise ValueError("Cannot find your default keychain. Unlock your login keychain and retry.")
    keychain = Path(paths[0])
    if (
        not keychain.is_absolute()
        or not keychain.is_file()
        or keychain.stat().st_uid != os.getuid()
        or keychain.resolve().is_relative_to("/Library/Keychains")
        or keychain.resolve().is_relative_to("/System/Library/Keychains")
    ):
        raise ValueError("Capture trust requires an existing keychain owned by the current user.")
    return keychain
